name: ⚠️ Security Vulnerability Report (Private Disclosure ONLY)
description: Report a security issue according to Tunnelsats' official responsible disclosure policy.
title: "[SECURITY]: DO NOT USE THIS FIELD - See Instructions Below"
body:
  - type: markdown
    attributes:
      value: |
        # 🚨 **STOP: Private Security Disclosure Required** 🚨

        **DO NOT OPEN A PUBLIC ISSUE FOR SECURITY PROBLEMS.**

        To protect all Tunnelsats users, any potential security vulnerabilities must be reported **privately**.

        **How to Report a Vulnerability:**
        1. **Read our full Responsible Disclosure Policy:** You can find the required private reporting method in our dedicated [**SECURITY.md file**](https://github.com/Tunnelsats/tunnelsats/blob/main/SECURITY.md).
        2. **Use the private method described there** (e.g., a specific email address or GitHub Security Advisory form).
        3. Do not proceed with this public issue form.

        Thank you for helping to secure Tunnelsats by following the private disclosure process.
